$(function() {
  $("#click1").click(function(){
    $("#content1").fadeToggle();
  });
  $("#click2").click(function(){
    $("#content2").toggle();
  });
  $("#click3").click(function(){
    $("#content3").toggle();
  });
  $("#click4").click(function(){
    $("#content4").toggle();
  });
  $("#click5").click(function(){
    $("#content5").fadeToggle();
  });
  $("#click6").click(function(){
    $("#content6").toggle();
  });
  $("#click7").click(function(){
    $("#content7").slideToggle();
  });
  $("#click8").click(function(){
    $("#content8").toggle();
  });
  $("#click9").click(function(){
    $("#content9").toggle();
  });
  $("#click17").click(function(){
    $("#content17").slideToggle();
  });
  $("#click10").click(function(){
    $("#content10").toggle();
  });
  $("#click11").click(function(){
    $("#content11").toggle();
  });
  $("#click12").click(function(){
    $("#content12").toggle();
  });
  $("#click13").click(function(){
    $("#content13").slideToggle();
  });
  $("#click14").click(function(){
    $("#content14").fadeToggle();
  });
  $("#click15").click(function(){
    $("#content15").fadeToggle();
  });
  $("#click16").click(function(){
    $("#content16").toggle();
  });
});
